version: '3.8'

services:
  db:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    container_name: video_annotation_db
    restart: always
    environment:
      POSTGRES_DB: video_annotation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: